name: Union Fashion
title: An API-First E-Commerce Reference Implementation
description: This is a fictional e-commerce company that provides an API-first reference implementation.
url: http://union.fashion

# Build settings
markdown: kramdown
