name: Union Fashion
title: An API-First E-Commerce Reference Implementation
description: This is a fictional e-commerce company that provides an API-first reference implementation.
url: http://developers.union.fashion

# Build settings
markdown: kramdown

paginate: 12
paginate_path: "/page/:num"
permalink: /:year/:month/:day/:title/

collections:
  apis:
    output: true
    permalink: /apis/:path/

defaults:
  - scope:
      type: apis
    values:
      layout: "apis"
